functionsDirectory = "C:\\Users\\tanis\\OneDrive\\Desktop\\skill_Notes-1\\skill_Notes\\netlify\\functions"
functionsDirectoryOrigin = "default"
headersOrigin = "config"
redirectsOrigin = "config"
plugins = []

[build]
publish = "C:\\Users\\tanis\\OneDrive\\Desktop\\skill_Notes-1\\skill_Notes\\dist"
publishOrigin = "config"
commandOrigin = "config"
command = "npm run build"
functions = "C:\\Users\\tanis\\OneDrive\\Desktop\\skill_Notes-1\\skill_Notes\\netlify\\functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[headers]]
for = "/*.html"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"

[[headers]]
for = "/pages/*.html"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"

[[headers]]
for = "/"

[headers.values]
Cache-Control = "no-cache, no-store, must-revalidate, max-age=0"
Pragma = "no-cache"
Expires = "0"

[[headers]]
for = "/js/*"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/css/*"

[headers.values]
Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
for = "/assets/*"

[headers.values]
Cache-Control = "public, max-age=31536000, immutable"

[[redirects]]
from = "/login.html"
to = "/pages/auth.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/auth.html"
to = "/pages/auth.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pages/login.html"
to = "/pages/auth.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pages/*"
to = "/pages/:splat.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/*"
to = "/404.html"
status = 404.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "https://skillnotes.netlify.app/*"
to = "https://skilmatrix.site/:splat"
status = 301.0
force = true

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/login"
to = "/pages/auth.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/auth"
to = "/pages/auth.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pages/login"
to = "/pages/auth.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pages/auth/*"
to = "/pages/auth.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pages/dashboard/*"
to = "/pages/dashboard.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/pages/codetantra/*"
to = "/pages/codetantra.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/notes/*"
to = "/pages/notes.html"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/share/*"
to = "https://skil-matrix-server.onrender.com/api/share/:splat"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]

[[redirects]]
from = "/subscription"
to = "https://skil-matrix-server.onrender.com/api/subscription-seo"
status = 200.0
force = false

[redirects.query]

[redirects.conditions]

[redirects.headers]